name: SoloPiano
favicon: null
layout_spectrum: 0.55926
typography_spectrum: 0.62566
title: SoloPiano.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afdff4'
    - '#283361'
    - '#969ac2'
    - '#7073ab'
  brandStrength: 0.18121539987623692
  lightness: 0.4886577764991671
  saturation: 0.10558504448272288
  rhythmicContrast: 0.31849210732616484
purpose: []
